### ISSUE TITLE
Plugin adds text to text boxes where you enter BCH addresses

### ISSUE THREAD

**Issue by JLMoriart** [sterlingbeason/SnappyCash#1]
For example, on YouTube,posting a comment with the following text:
"bitcoincash:qqsaruf36d5dlcy5zhcv4r8y0z2gl9txxc734pggw2"
will result in a comment with the text 
"bitcoincash:qqsaruf36d5dlcy5zhcv4r8y0z2gl9txxc734pggw2
Badger Wallet
$0.00
send"

**Comment by sterlingbeason** [comment]
@JLMoriart Sorry for the delay. I didn't see this issue for whatever reason. I was able to replicate your issue. 
The issue is from editable HTML elements; such as a 'div'. This is something the extension was designed to look for and avoid, but it was done with an incorrect method. There is a fix coming for this.

**Comment by JLMoriart** [comment]
Great, thanks! I still use SnappyCash all the time!
